In [2]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import csv

In [13]:
df = pd.read_csv('Parking_Violations_Issued_-_Fiscal_Year_2021.csv',encoding='utf-8',nrows = 100000,skipinitialspace=True,low_memory=False)

In [14]:
df

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,...,Vehicle Color,Unregistered Vehicle?,Vehicle Year,Meter Number,Feet From Curb,Violation Post Code,Violation Description,No Standing or Stopping Violation,Hydrant Violation,Double Parking Violation
0,1471497410,HZH8177,NY,PAS,07/02/2020,20,SUBN,NISSA,P,62200,...,GRAY,0.0,2018,-,0,NaN,NaN,NaN,NaN,NaN
1,1471497630,JCX5781,NY,PAS,06/27/2020,20,P-U,DODGE,P,60790,...,BLU,0.0,2018,-,0,NaN,NaN,NaN,NaN,NaN
2,1471497641,HEK2391,NY,PAS,06/27/2020,20,SUBN,KIA,P,60790,...,BLU,0.0,2020,-,0,NaN,NaN,NaN,NaN,NaN
3,1471497653,GWY9859,NY,PAS,06/27/2020,20,SUBN,JEEP,P,60790,...,BLK,0.0,2009,-,0,NaN,NaN,NaN,NaN,NaN
4,1471497665,HEZ5501,NY,PAS,06/27/2020,20,SUBN,SUBAR,P,60790,...,BLK,0.0,2015,-,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,4698329735,HVF2188,NY,PAS,07/10/2020,36,4DSD,SUBAR,V,0,...,BK,NaN,2015,NaN,0,NaN,PHTO SCHOOL ZN SPEED VIOLATION,NaN,NaN,NaN
99996,4698329747,HWY1702,NY,PAS,07/10/2020,36,4DSD,AUDI,V,0,...,GY,NaN,2010,NaN,0,NaN,PHTO SCHOOL ZN SPEED VIOLATION,NaN,NaN,NaN
99997,4698329759,HCS1873,NY,PAS,07/10/2020,36,SUBN,HONDA,V,0,...,BK,NaN,2016,NaN,0,NaN,PHTO SCHOOL ZN SPEED VIOLATION,NaN,NaN,NaN
99998,4698329760,JAB5978,NY,PAS,07/10/2020,36,4DSD,DODGE,V,0,...,BL,NaN,2018,NaN,0,NaN,PHTO SCHOOL ZN SPEED VIOLATION,NaN,NaN,NaN
99999,4698329772,JBX6915,NY,PAS,07/10/2020,36,SUBN,TOYOT,V,0,...,WH,NaN,2018,NaN,0,NaN,PHTO SCHOOL ZN SPEED VIOLATION,NaN,NaN,NaN

In [17]:
df['Violation Post Code'].iloc[0]

nan

In [18]:
f = pd.read_csv('new sheet.csv')
f

   hello   there
0       1    2.0
1       3    NaN
2       5    6.0

In [ ]:
df[df['Vehicle Year']==2017]

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,...,Vehicle Color,Unregistered Vehicle?,Vehicle Year,Meter Number,Feet From Curb,Violation Post Code,Violation Description,No Standing or Stopping Violation,Hydrant Violation,Double Parking Violation
37,1471503630,HVV4878,NY,PAS,06/22/2020,50,SDN,HYUND,P,29887,...,WHITE,0.0,2017,-,0,NaN,NaN,NaN,NaN,NaN
68,1471515382,GHR5914,NY,PAS,06/27/2020,98,SDN,INFIN,P,19340,...,GRAY,0.0,2017,-,0,NaN,NaN,NaN,NaN,NaN
122,1473991274,HUE5220,NY,PAS,06/25/2020,48,SDN,HONDA,P,25800,...,BLK,0.0,2017,-,0,NaN,NaN,NaN,NaN,NaN
124,1473991330,HDY5373,NY,PAS,06/26/2020,48,SUBN,LEXUS,P,25800,...,WH,0.0,2017,-,0,NaN,NaN,NaN,NaN,NaN
126,1473991377,HTS4872,NY,PAS,06/28/2020,48,SDN,TOYOT,P,25800,...,GRY,0.0,2017,-,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9934,4013929727,JNM3936,NY,PAS,05/30/2020,5,4DSD,ME/BE,V,0,...,GR,NaN,2017,NaN,0,NaN,BUS LANE VIOLATION,NaN,NaN,NaN
9956,4013930079,M12LDF,NJ,PAS,05/30/2020,5,SD,HONDA,V,0,...,NaN,NaN,2017,NaN,0,NaN,BUS LANE VIOLATION,NaN,NaN,NaN
9966,4013930237,HWE9296,NY,PAS,05/30/2020,5,SUBN,SUBAR,V,0,...,GY,NaN,2017,NaN,0,NaN,BUS LANE VIOLATION,NaN,NaN,NaN
9984,4013930547,HMP3084,NY,PAS,05/30/2020,5,SUBN,BUICK,V,0,...,WH,NaN,2017,NaN,0,NaN,BUS LANE VIOLATION,NaN,NaN,NaN
9990,4013930626,HSJ3015,NY,PAS,05/30/2020,5,SUBN,JEEP,V,0,...,BK,NaN,2017,NaN,0,NaN,BUS LANE VIOLATION,NaN,NaN,NaN

In [5]:
df['Vehicle Year'].isnull().any()

False

In [6]:
df['Vehicle Body Type'].value_counts()

SUBN    4653
SDN     3739
4DSD     571
VAN      192
P-U      137
        ...
MC         1
I          1
TOW        1
OIGI       1
TRK        1
Name: Vehicle Body Type, Length: 66, dtype: int64

In [7]:
df.isnull().any()

Summons Number                       False
Plate ID                             False
Registration State                   False
Plate Type                           False
Issue Date                           False
Violation Code                       False
Vehicle Body Type                     True
Vehicle Make                          True
Issuing Agency                       False
Street Code1                         False
Street Code2                         False
Street Code3                         False
Vehicle Expiration Date              False
Violation Location                    True
Violation Precinct                   False
Issuer Precinct                      False
Issuer Code                          False
Issuer Command                        True
Issuer Squad                          True
Violation Time                        True
Time First Observed                   True
Violation County                      True
Violation In Front Of Or Opposite     True
House Number                          True
Street Name                           True
Intersecting Street                   True
Date First Observed                  False
Law Section                          False
Sub Division                          True
Violation Legal Code                  True
Days Parking In Effect                True
From Hours In Effect                  True
To Hours In Effect                    True
Vehicle Color                         True
Unregistered Vehicle?                 True
Vehicle Year                         False
Meter Number                          True
Feet From Curb                       False
Violation Post Code                   True
Violation Description                 True
No Standing or Stopping Violation     True
Hydrant Violation                     True
Double Parking Violation              True
dtype: bool

In [8]:
list(df.columns).index('Vehicle Body Type')

6

In [9]:
list(df.columns).index('Vehicle Year')

35

In [10]:
df['Vehicle Body Type'].value_counts()

SUBN    4653
SDN     3739
4DSD     571
VAN      192
P-U      137
        ...
MC         1
I          1
TOW        1
OIGI       1
TRK        1
Name: Vehicle Body Type, Length: 66, dtype: int64

In [11]:
import re

In [12]:
a = 'Vehicle There'
pat = re.compile(r'^[a-zA-Z]+\S$')
print(pat.search(a))

None

In [13]:
num_pat = re.compile(r'^\d\d\d\d$')
b = '1235'
print(num_pat.search(b)[0])

1235

In [14]:
print(str(""))

In [15]:
file = open('new sheet.csv','r')

data = file.readlines()

for line in data:
    line = line.strip()
    line = line.split(',')
    print(line)





file.close()

['hello ', 'there']
['1', '2']
['3', '']
['5', '6']

In [26]:
file = open('Parking_Violations_Issued_-_Fiscal_Year_2022.csv')

In [27]:
data = file.readlines()

In [28]:
data = iter(data)

In [29]:
next(data)
# data = list(data)
c = 0
for line in data:
    line = line.strip()
    line = line.split(',')
    if c==3:
        break
    c+=1
    print(line)

['1457617912', 'JEB5683', 'NY', 'PAS', '06/25/2021', '40', 'VAN', 'FORD', 'P', '63430', '69230', '13490', '20221004', '0088', '88', '88', '967603', '0088', '0000', '0130A', '0125A', 'K', 'O', '100', 'NORTH PORTLAND AVE', '', '0', '408', 'C4', '', 'BBBBBBB', 'ALL', 'ALL', 'GY', '0', '2007', '-', '3', '', '', '', '', '']
['1457617924', 'JAN2986', 'NY', 'PAS', '06/25/2021', '20', 'SUBN', 'DODGE', 'P', '13490', '40404', '40404', '20221203', '0088', '88', '88', '967603', '0088', '0000', '0225A', '0215A', 'K', 'F', '398', 'AUBURN PLACE', '', '20210625', '408', 'E2', '', 'BBBBBBB', 'ALL', 'ALL', 'BLU', '0', '2007', '-', '0', '', '', '', '', '']
['1457622427', 'FJH6630', 'TX', 'PAS', '06/17/2021', '98', 'SDN', 'AUDI', 'P', '79430', '47130', '11750', '0', '0088', '88', '88', '969730', '0088', '0000', '0809P', '', 'K', 'F', '170', 'SOUTH PORTLAND AVE', '', '0', '408', 'E2', '', 'BBBBBBB', 'ALL', 'ALL', 'WHITE', '0', '0', '-', '0', '', '', '', '', '']

In [22]:
next(data)

'1457617912,JEB5683,NY,PAS,06/25/2021,40,VAN,FORD,P,63430,69230,13490,20221004,0088,88,88,967603,0088,0000,0130A,0125A,K,O,100,NORTH PORTLAND AVE,,0,408,C4,,BBBBBBB,ALL,ALL,GY,0,2007,-,3,,,,,\n'

In [39]:
f = open('Parking_Violations_Issued_-_Fiscal_Year_2022.csv','r')
variable = csv.DictReader(f)

In [40]:
c = 0
for line in variable:
    print(line['Vehicle Body Type'])
    if c==3:
        break
    c+=1

VAN
SUBN
SDN
SDN

In [47]:
from operator import itemgetter
import sys
import re
import errno

f_handle = open('Parking_Violations_Issued_-_Fiscal_Year_2022.csv')

c = 0
create_list = list()
data = f_handle.readlines()
# data = iter(data)
# next(data)
# year_pat = re.compile(r'^\d\d\d\d$')
# body_type_pat = re.compile(r'^[a-zA-Z]+\S$')
for line in data:
    line = line.strip()
    line = line.split(',')

    year = str(line[35])

    if not (year!= '' and year!="Vehicle Year" and (int(year) > 1900 and int(year) < 2023)):
        continue           # skipping rows with invalid registration year data

    bodyType = str(line[6])

    if bodyType == "" or " " in bodyType or bodyType == "Vehicle Body Type":
        continue          # skipping rows with missing values of those containing spaces



    a = year+"_"+bodyType+"\t"+"1"
    create_list.append(a)


    if c==10:
        break

    c+=1
    # try:
    #     reg_year = year_pat.search(line[35])
    # except:
    #     reg_year = "None"

    # if reg_year:
    #     reg_year = reg_year[0]
    # body_type = body_type_pat.search(line[6])

    # if  body_type and line[6]!="Vehicle Body Type":
    #     body_type = body_type[0]
    # else:
    #     body_type = "None"

    # if c==3:
    #     break
    # print(reg_year+"\t"+body_type)


f_handle.close()

In [50]:
for item in create_list:
    print(item)

2007_VAN	1
2007_SUBN	1
2001_SDN	1
2020_TAXI	1
2015_SDN	1
2015_SDN	1
2015_SDN	1
2017_SUBN	1
2017_SUBN	1
2001_SDN	1
2015_SDN	1

In [54]:
b = create_list[0]

In [56]:
b = b.split()
year = b[0].split('_')[0]
type = b[0].split('_')[1]
num = int(b[1])
print(year)
print(type)
print(num)

2007
VAN
1

In [52]:
#! /c/Users/rahul.ohlan/AppData/Local/Microsoft/WindowsApps/python

from operator import itemgetter
import sys

import re
import errno

year_dict = dict()
type_dict = dict()

for line in create_list:

    line = line.strip()
    year = line.split('_')[0]
    b_type = line.split('_')[1].split('\t')[0]
    num = line.split('_')[1].split('\t')[1]
    num = int(num)

    year_dict[year] = year_dict.get(year,0) + num
    type_dict[b_type] = type_dict.get(b_type,0) + num


sorted_years = sorted(year_dict.items(), key = itemgetter(1),reverse=True)
sorted_types = sorted(type_dict.items(), key = itemgetter(1),reverse=True)

print('top 5 years: ',end=' ')
print(sorted_years[0:5])
print('top 5 car types: ',end=' ')
print(sorted_types[0:5])





    # print(year,b_type)

    # print(line,end='')

top 5 years:  [('2015', 4), ('2007', 2), ('2001', 2), ('2017', 2), ('2020', 1)]
top 5 car types:  [('SDN', 6), ('SUBN', 3), ('VAN', 1), ('TAXI', 1)]